 name: instronova_app
description: A social media app like Instagram
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  image_picker: ^1.0.4
  video_player: ^2.8.2
  intl: ^0.18.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/default_avatar.png

  fonts:
    - family: Cursive
      fonts:
        - asset: fonts/Cursive-Regular.ttf

