name: instagram_clone
description: A fully featured social media app like Instagram
publish_to: 'none' # Remove this line to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.1.1
  image_picker: ^0.8.7+5
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  intl: ^0.18.0
  flutter_staggered_grid_view: ^0.6.2
  url_launcher: ^6.1.11
  firebase_core: ^2.24.0
  firebase_auth: ^4.7.0
  cloud_firestore: ^5.9.0
  firebase_storage: ^11.3.0
  flutter_local_notifications: ^19.4.2
  flutter_keyboard_visibility: ^5.4.1
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  animated_text_kit: ^4.2.2
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
          style: italic
