 name: instagram_clone
description: A fully featured social media app like Instagram
publish_to: 'none' # Remove this line to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  get: ^4.6.5
  provider: ^6.0.5

  # Networking
  http: ^1.1.0

  # Storage & local data
  shared_preferences: ^2.2.2

  # Media & UI
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.3.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  animated_text_kit: ^4.2.2
  google_fonts: ^6.2.1

  # Firebase
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.4

  # Notifications & utilities
  flutter_local_notifications: ^19.4.2
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
          style: italic

