# Podfile for Instagram-like iOS Application
platform :ios, '14.0'
use_frameworks!
use_modular_headers!
inhibit_all_warnings!

# Main App Target
target 'MyApp' do
  
  # Firebase & Google Services
  pod 'Firebase/Core', '~> 10.0'
  pod 'Firebase/Auth', '~> 10.0'
  pod 'Firebase/Firestore', '~> 10.0'
  pod 'Firebase/Storage', '~> 10.0'
  pod 'Firebase/Messaging', '~> 10.0'
  pod 'Firebase/Crashlytics', '~> 10.0'
  pod 'Firebase/RemoteConfig', '~> 10.0'
  
  # Social Media SDKs & Sign-In
  pod 'FBSDKLoginKit', '~> 16.0'
  pod 'TwitterKit', '~> 3.4'
  pod 'TikTokOpenSDK', '~> 5.0'
  pod 'SnapSDK', '~> 1.8'
  
  # UI / UX Enhancements
  pod 'SDWebImage', '~> 5.15'
  pod 'Lottie', '~> 4.4'
  pod 'SkeletonView', '~> 1.30'
  pod 'IQKeyboardManagerSwift', '~> 6.5'
  
  # Networking & APIs
  pod 'Alamofire', '~> 5.8'
  pod 'Moya', '~> 15.0'
  pod 'Socket.IO-Client-Swift', '~> 16.1'
  
  # Media & Camera Features
  pod 'TOCropViewController', '~> 2.6'
  pod 'GPUImage3', '~> 3.0'
  pod 'ImagePicker', '~> 5.0'
  pod 'FFmpegKit', '~> 5.1'
  
  # Maps & Location
  pod 'GoogleMaps', '~> 8.0'
  pod 'GooglePlaces', '~> 8.0'
  
  # Security
  pod 'KeychainAccess', '~> 4.2'
  
  # Others
  pod 'Branch', '~> 2.0'
  pod 'RealmSwift', '~> 10.45'
  pod 'Sentry', '~> 8.20'
  
end

# Post Install Hooks
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
